---
title: "Writing Functions"
author: "Jeff Goldsmith"
date: "11/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Simple function

```{r}
set.seed(1)

x = rnorm(25)

mean(x) / sd(x)
```

Let's see this as a function...

```{r}
z_score = function(x) {
  
  z = mean(x) / sd(x)
  
  z
  
}

z_score(x)
```

Unintended argument values ...

```{r, error = TRUE}
z_score(19.375)
z_score("my name is jeff")
z_score(iris)
z_score(c(TRUE, TRUE, FALSE, TRUE))
```

Add some control statements.

```{r}
z_score = function(x) {
  
  if (!is.numeric(x)) {
    stop("x must be numeric")
  } else if (length(x) < 3) {
    stop("x must have three or more entries")
  }
  
  z = mean(x) / sd(x)
  
  z
  
}
```

## Multiple outputs

Add mean and sd to output ...


```{r}
z_score = function(x) {
  
  if (!is.numeric(x)) {
    stop("x must be numeric")
  } else if (length(x) < 3) {
    stop("x must have three or more entries")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  z = mean_x / sd_x
  
  data_frame(mean = mean_x,
             sd = sd_x,
             z = z)
  
}

z_score(x)
```


### A bit more interesting ...

Starting code.

```{r}
sim_data = tibble(
  x = runif(30),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ggplot(sim_data, aes(x = x, y = y)) + geom_point()

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]
```

Let's write a function to simulate SLR and produce estimates ...

```{r}
sim_regression = function(n, beta0, beta1) {
  
  sim_data = tibble(
    x = runif(n),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )

  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
  
}
```


